"""Convert a `.tflite` file plus a label list into the C/C++ source pair
(`model_data.cc` + `model_data.h`) consumed by `tflm_demo/`.

The header also exports the input feature shape and label count used by
`kws_inference.cc` / `main.cc`, so different models (DS-CNN, GRU-S/M/L, …)
can be plugged in by swapping the `MODEL_DIR` Makefile variable without
touching the C++ code.

Usage:
    python tools/tflite_to_cc.py \
        --tflite artifacts/gru_M/gru/model_int8.tflite \
        --output-dir artifacts/gru_M \
        --frames 49 --bins 40 --channels 1 \
        --labels yes,no,up,down,left,right,on,off,stop,go,_unknown_,_silence_
"""
from __future__ import annotations

import argparse
import textwrap
from pathlib import Path
from typing import Iterable, List


def _hex_array(data: bytes, line_width: int = 12) -> str:
    chunks: List[str] = []
    for i in range(0, len(data), line_width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + line_width])
        chunks.append("    " + chunk + ",")
    return "\n".join(chunks).rstrip(",")


def _format_label_array(labels: Iterable[str]) -> str:
    quoted = [f'    "{label}"' for label in labels]
    return ",\n".join(quoted)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tflite", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--frames", type=int, required=True)
    parser.add_argument("--bins", type=int, required=True)
    parser.add_argument("--channels", type=int, default=1)
    parser.add_argument(
        "--labels",
        type=str,
        required=True,
        help="Comma-separated label list, in model output order.",
    )
    parser.add_argument("--symbol", type=str, default="model_int8_tflite")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    tflite_bytes = args.tflite.read_bytes()
    labels = [s.strip() for s in args.labels.split(",") if s.strip()]
    args.output_dir.mkdir(parents=True, exist_ok=True)

    header = textwrap.dedent(
        f"""\
        // Auto-generated by tools/tflite_to_cc.py — DO NOT EDIT.
        #ifndef KWS_GENERATED_MODEL_DATA_H_
        #define KWS_GENERATED_MODEL_DATA_H_

        #include <cstddef>

        namespace kws {{

        constexpr int kFeatureFrames = {args.frames};
        constexpr int kFeatureBins = {args.bins};
        constexpr int kFeatureChannels = {args.channels};
        constexpr int kFeatureElementCount =
            kFeatureFrames * kFeatureBins * kFeatureChannels;
        constexpr int kCategoryCount = {len(labels)};

        extern const char* const kCategoryLabels[kCategoryCount];

        }}  // namespace kws

        extern const unsigned char {args.symbol}[];
        extern const unsigned int {args.symbol}_len;

        #endif  // KWS_GENERATED_MODEL_DATA_H_
        """
    )

    source = textwrap.dedent(
        f"""\
        // Auto-generated by tools/tflite_to_cc.py — DO NOT EDIT.
        #include "model_data.h"

        alignas(16) const unsigned char {args.symbol}[] = {{
        {_hex_array(tflite_bytes)}
        }};
        const unsigned int {args.symbol}_len = {len(tflite_bytes)};

        namespace kws {{

        const char* const kCategoryLabels[kCategoryCount] = {{
        {_format_label_array(labels)}
        }};

        }}  // namespace kws
        """
    )

    (args.output_dir / "model_data.h").write_text(header)
    (args.output_dir / "model_data.cc").write_text(source)
    print(
        f"Wrote {args.output_dir / 'model_data.cc'} "
        f"({len(tflite_bytes)} bytes of model, {len(labels)} labels)"
    )


if __name__ == "__main__":
    main()
