#!/usr/bin/env python3
"""Emit TFLM-compatible C source for a .tflite model.

Writes two files:
  <out-dir>/model_data.h  - declarations for `model_int8_tflite` / `_len`
  <out-dir>/model_data.cc - 16-byte-aligned const byte array + length

These symbol names are what tflm_demo/kws_inference.cc expects. Running this
script is the "convert the int8 tflite into a C array" step from the README
deployment pipeline — replaces running `xxd -i` manually.
"""
import argparse
import os
from pathlib import Path


HEADER_TEMPLATE = """// Auto-generated by tools/tflite_to_model_data.py. Do not edit by hand.
// Source: {source}
#ifndef KWS_{guard}_MODEL_DATA_H
#define KWS_{guard}_MODEL_DATA_H

extern const unsigned char model_int8_tflite[];
extern const unsigned int model_int8_tflite_len;

#endif
"""

SOURCE_TEMPLATE = """// Auto-generated by tools/tflite_to_model_data.py. Do not edit by hand.
// Source: {source}
#include "{rel_header}"

alignas(16) const unsigned char model_int8_tflite[] = {{
{bytes}
}};

const unsigned int model_int8_tflite_len = {length}u;
"""


def format_bytes(data: bytes, bytes_per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i : i + bytes_per_line]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--tflite", required=True, type=Path, help="Input .tflite file")
    p.add_argument("--out-dir", required=True, type=Path, help="Destination directory for model_data.{cc,h}")
    p.add_argument(
        "--guard",
        default=None,
        help="Optional include guard stem (defaults to the out-dir basename uppercased).",
    )
    args = p.parse_args()

    data = args.tflite.read_bytes()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    guard = (args.guard or args.out_dir.name).upper().replace("-", "_")
    header_path = args.out_dir / "model_data.h"
    source_path = args.out_dir / "model_data.cc"

    source_rel = os.path.relpath(args.tflite.resolve(), start=args.out_dir.resolve())
    header_rel = "model_data.h"  # source lives next to the header

    header_path.write_text(HEADER_TEMPLATE.format(source=source_rel, guard=guard))
    source_path.write_text(
        SOURCE_TEMPLATE.format(
            source=source_rel,
            rel_header=header_rel,
            bytes=format_bytes(data),
            length=len(data),
        )
    )

    print(f"Wrote {header_path}  ({len(data)} bytes tflite)")
    print(f"Wrote {source_path}")


if __name__ == "__main__":
    main()
